version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build test image
          command: docker-compose -f docker-compose.test.yml build
      - run:
          name: Run tests
          command: docker-compose -f docker-compose.test.yml run --rm bork_test
